eureka:
  client:
    serviceUrl:
      defaultZone: http://root:993928@127.0.0.1:10001/eureka/,http://root:993928@127.0.0.1:10002/eureka/,http://root:993928@127.0.0.1:10003/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}

server:
  port: 10023
spring:
  profiles:
    active: native #开启本地配置文件
  application:
    name: server-gang-config #这在以后的服务与服务之间相互调用一般都是根据这个name
    index: ${eureka.instance.instance-id}
  cloud:
    bus: #消息总线配置,/bus/refresh全部刷新，/bus/refresh?destination=customers:** 即刷新服务名为customers的所有服务，/bus/env发送键/值对来更新每个节点的环境
      trace: #要使用POST请求刷新
        enabled: true #/trace查看bus事件
    config:
      server: #config-server不能使用配置中心，原因是项目启动时不去加载配置文件，同时也不能是用springboot多环境启动，开启本地占用了active，尚不知道git方式能不能用
        native:
          #search-locations: I:/cloud-config #注意路径分割符即便是win也是/
          #search-locations: /u01/gang/cloud-config
          search-locations: classpath:ymls/  #可以存在项目路径下
        #git:
          #uri: https://github.com/liangjiagang/com-gang #服务的git仓库地址
          #search-paths: /files-gang-config/src #配置文件所在的目录
          #username: liangjiagang
          #password: gang813928
      #label: master #配置文件所在的分支

management:
  security:
    enabled: false
    #enabled: true #bus刷新时，开启安全验证



