spring:
  thymeleaf:
    cache: false #启用模板缓存（开发时建议关闭）
    check-template: true #检查模板是否存在，然后再呈现
    check-template-location: true #检查模板位置是否存在
    enabled: true #启用MVC Thymeleaf视图分辨率
    # 以下是默认配置
    prefix: classpath:/templates/
    suffix: .html
    #mode: HTML #官方推荐的格式
    mode: HTML5  #据说是默认值
    #mode: LEGACYHTML5 #用于不严格的html格式检查，需要配合jar包
    encoding: UTF-8
    content-type: text/html