
#zuul路径映射，/routes?format=details查看映射信息,只能做服务转发,不能做页面转发,会找不到静态文件
zuul:
  routes:
    api-a:
      path: /test1/**
      serviceId: service-gang-test1
    api-b:
      path: /test2/**
      serviceId: service-gang-test2
    api-c:
      path: /test3/**
      serviceId: service-gang-test3
    api-d:
      path: /**
      serviceId: service-gang-web
      stripPrefix: true
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
  add-host-header: true   # 此处解决后端服务重定向导致用户浏览的 host 变成 后端服务的 host 问题


#rabbitmq配置
spring:
  rabbitmq:
    host: localhost
    password: cloud
    port: 5672
    username: cloud
    virtual-host: /cloud
      